ci(GLOBAL): test reporter without test files

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,21 +31,23 @@ jobs:
       #     echo Creating .env file...
       #     echo "$TEST_ENV_VARS" | base64 -d > .env
 
-      # - name: Run tests
-      #   run: |
-      #     npm ci
-      #     npm test
-
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure()    # run this step even if previous step failed
-      #   with:
-      #     name: JEST Tests            # Name of the check run which will be created
-      #     path: reports/jest-*.xml    # Path to test results
-      #     reporter: jest-junit        # Format of test results
-
-      - name: Release
+      - name: Run tests
         run: |
-          git config user.name "GitHub Actions Bot"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          npm run version:patch
+          npm ci
+          npm test
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
+
+      - name: Post step
+        run: echo "Hi, I'm a post step running after JEST report"
+      # - name: Release
+      #   run: |
+      #     git config user.name "GitHub Actions Bot"
+      #     git config user.email "github-actions[bot]@users.noreply.github.com"
+      #     npm run version:patch
